# Generated by Django 5.1.7 on 2025-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
